highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://yogayu.github.io/cv/
author: 游薪渝

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: http://yogayu.github.io/cv/
title: 游薪渝的简历
name: 游薪渝
email: youxinyu07@qq.com
email_full: mailto:youxinyu07@qq.com
website: http://data2art.com
website_full: http://data2art.com
github: yogayu
twitter: yxydiscovery
weibo: yxydiscovery
tel: +86 18002334858
tel_full: tel:+86 18002334858
postcode: 401331
city: 重庆市
country: 中国
google_analytics: UA-78816000-1

# needed for travis-ci build
exclude: [vendor]
